docs: Update issue template
bank-vaults/vault-sdk pull request #132
Opened 2023-08-03 05:36 UTC by tanmay-pnaik

## Overview

Add issue template

## Notes for reviewer

Adapted from https://github.com/bank-vaults/vault-operator/tree/main/.github/ISSUE_TEMPLATE

2023-08-04 22:58 UTC, sagikazarmark requested changes

2023-08-04 22:58 UTC, sagikazarmark commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      required: true
```suggestion
```

This information does not seem relevant for the SDK.

2023-08-04 22:58 UTC, sagikazarmark commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      render: shell
```suggestion
```

Same as above

2023-08-04 23:12 UTC, sagikazarmark requested changes

2023-08-04 23:12 UTC, sagikazarmark commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +labels: [bug]
```suggestion
labels: [kind/bug]
```

2023-08-04 23:12 UTC, sagikazarmark commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +          required: true
```suggestion
          required: true
        - label: I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).
          required: true
```

2023-08-04 23:12 UTC, sagikazarmark commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +          required: true
```suggestion
```suggestion
          required: true
        - label: I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).
          required: true
```
```

2023-08-04 23:12 UTC, sagikazarmark commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +description: Suggest an idea for the Vault SDK
```suggestion
description: Suggest an idea for the Vault SDK
labels: [kind/enhancement]
```

2023-08-30 14:41 UTC, ramizpolic requested changes

2023-08-30 14:41 UTC, ramizpolic commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Check the documentation for help
```suggestion
  - name: 📚 Documentation
    url: https://bank-vaults.dev/docs/go-library/
    about: Check the documentation for help
    
  - name: 📖 Documentation enhancement
    url: https://github.com/bank-vaults/bank-vaults.dev/issues
    about: Suggest an improvement to the documentation
```

2023-08-30 14:41 UTC, ramizpolic commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +        - label: I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-sdk/issues) for an issue that matches the one I want to file, without success.
```suggestion
        - label: I have checked the [issue tracker](https://www.github.com/bank-vaults/vault-sdk/issues) and found no issue that matches the one I want to submit.
```

2023-08-30 18:58 UTC, ramizpolic commented
Much appreciated @tanmay-pnaik, this is awesome! Would you mind fixing the pipeline issues? I can merge it afterward.

2023-08-30 19:05 UTC, tanmay-pnaik commented
> Much appreciated @tanmay-pnaik, this is awesome! Would you mind fixing the pipeline issues? I can merge it afterwards.

Done!

2023-08-30 19:11 UTC, ramizpolic approved these changes

2023-08-30 19:16 UTC, ramizpolic commented on .github/ISSUE_TEMPLATE/config.yml
> -
The lint check was failing due to trailing spaces. I removed it via GitHub UI. AFAIK There is no need for more than one person to sign the commit. 

Also, similar changes should be added to other PRs. This is very useful for the project as a whole, so thanks again @tanmay-pnaik 🚀

2023-08-30 19:34 UTC, tanmay-pnaik commented on .github/ISSUE_TEMPLATE/config.yml
> -
@ramizpolic Have already created similar PRs across the project! :grin:

2023-08-31 09:07 UTC, sagikazarmark approved these changes

2023-08-31 09:07 UTC, merged